-- AlterTable
ALTER TABLE "SiteSettings"
ADD COLUMN "textColor" TEXT NOT NULL DEFAULT '#1c232c',
ADD COLUMN "headingColor" TEXT NOT NULL DEFAULT '#141a22',
ADD COLUMN "mutedColor" TEXT NOT NULL DEFAULT '#3f4b58',
ADD COLUMN "hintColor" TEXT NOT NULL DEFAULT '#5a6570',
ADD COLUMN "placeholderColor" TEXT NOT NULL DEFAULT '#6b7682',
ADD COLUMN "textColorDark" TEXT NOT NULL DEFAULT '#ede8e1',
ADD COLUMN "headingColorDark" TEXT NOT NULL DEFAULT '#f5f1ea',
ADD COLUMN "mutedColorDark" TEXT NOT NULL DEFAULT '#c9c2b8',
ADD COLUMN "hintColorDark" TEXT NOT NULL DEFAULT '#b8b0a6',
ADD COLUMN "placeholderColorDark" TEXT NOT NULL DEFAULT '#a39b91';
